# Generated by Django 5.0.6 on 2024-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_rename_price_per_hout_expertprofile_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercaloryprofile',
            name='height',
            field=models.FloatField(default=170),
        ),
    ]
