# Generated by Django 5.0.6 on 2024-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expertise', '0006_alter_experttimetable_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='experttimetable',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
